---
- name: Stop a service
  win_service:
    name: spooler
    state: stopped
# tasks file for ReinicioServicio
- name: Start a service
  win_service:
    name: spooler
    state: started
  register: result

- debug:
    var: result
    verbosity: 2
